[general]
import = [ "gruvbox.toml" ]

[window]
padding = { x = 5, y = 5 }
decorations = "None"
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 15.0

